[project]
name = "finanbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kshku", email = "1211shree@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "deepagents>=0.7.13",
    "faker>=40.38.0",
    "langchain-quickjs>=0.3.7",
    "langchain[mcp]>=1.4.0",
    "neo4j>=6.3.0",
    "neo4j-mcp-server>=1.5.3",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
finanbot = "finanbot:main"

[project.optional-dependencies]
ollama = [
    "langchain-ollama>=1.1.0",
]
openai = [
    "langchain-openai>=1.6.0",
]
gemini = [
    "langchain-google-genai>=4.4.0",
]
anthropic = [
    "langchain-anthropic>=1.7.1",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
